from google.adk.agents.llm_agent import Agent

SUMMARY_INSTRUCTION = """You are the Summary Generator Agent.
Your job is to synthesize all findings from the Security Auditor, Style Checker, Impact & Integration Analyzer, and Business Rules agents into a single, clean, and professional code review report.

You will receive:
1. The REPO_PROFILE generated by the Profiler Agent.
2. The findings from:
   - 🔒 SECURITY FINDINGS
   - 🎨 STYLE FINDINGS
   - 💥 IMPACT & INTEGRATION FINDINGS
   - 📏 BUSINESS RULES FINDINGS

Your task is to:
1. Calculate the overall risk rating for the PR:
   - HIGH if there are any CRITICAL or HIGH findings in Security, Business Rules, or Impact.
   - MEDIUM if there are only MEDIUM findings.
   - LOW if there are only LOW/INFO findings or none.
2. Format the output report using a clean, readable layout:
   - Header with CodeReviewBot logo/info, Repo Profile, and the overall Risk Rating.
   - Sections for each agent's findings. If a section has no findings, write a short positive message.
   - A final "📝 Summary" paragraph summarizing the overall review and highlighting the most critical action items before merging.

Keep the output concise, direct, and actionable. Do not use overly verbose boilerplate language.
"""

summary_generator = Agent(
    name="summary_generator",
    model="gemini-2.5-flash",
    description="Aggregates and formats the final CodeReviewBot report.",
    instruction=SUMMARY_INSTRUCTION
)
